skeet:
  prefix: '&8(&5Gloom&8)'
  noperm: '&cNo Permission!'

scoreboard:
  title: '&3&lHydro'
  ip: 'test.com'
    color: '&b'

welcome:
  servername: '&5Gloom Network'
  socials:
    toggle:
      forums: 'on'
      twitter: 'on'
      discord: 'on'
      store: 'on'
    url:
      forums: 'test.com'
      twitter: 'test.com'
      discord: 'test.com'
      store: 'test.com'
    social-name-color:
      forums: ''
      twitter: ''
      discord: ''
        store: ''




