hub:
  prefix: '&d&lGloom &7|'
  nopermission: '&cNo Permission!'
  unknowncommand: '&cUnknown Command.'
  blockedcommands:
    - 'pl'
    - 'plugins'
    - 'about'
    - 'ver'
    - 'version'
    - 'pex'
    - '?'
  theme: '&6'



welcome:
  servername: '&7the &d&lGloom Network'
  message:
    - '&7&m----------------'
    - ' &7* &dSocial: &7https://yourlink.com'
    - ' &7* &dSocial: &7https://yourlink.com'
    - ' &7* &dSocial: &7https://yourlink.com'
    - '&7&m----------------'


scoreboard:
  title: '&d&lGloom Network'
  theme: '&d'
  serverip: '&7play.gloom.com'

help:
  message:
    - 'Contact support'
    - 'Contact support'