name: ${project.name}
main: com.skeet.skeethub.Main
version: ${project.version}
author: aston
depend: [Vault]

commands:
  links:
    aliases: [discord, twitter, forums, store, youtube]
  message:
    aliases: [pm, m, msg]
  hubreload:
    aliases: [hrl, hubrl]
  build:
  help:
    aliases: [support]